### ISSUE TITLE
Initial TODOs

### ISSUE THREAD

**Issue by Nick-Rivera** [DeclareDesign/declaredesign.org#3]
- [x] add the logo back to the config file, and just remove it from the header
- [x] Create a new homepage for the project that isn’t about the DD package itself along with a blog both using blogdown. So declaredesign.org will be run by blogdown. The Idea page can go on there and the Design Library, but Using DeclareDesign and Reference go into the package
- [x] Two-way factorial won’t render. Figure out why. 
- [ ] Pick a better font size
- [ ] Add a groovy logo
- [ ] Work on setting up the logos we developed into the hexagon package
- [x] Figure out a way to build the design library via blogdown (currently haxored in pkgdown I think)
- [x] Reorganize the web site stuff into a single Git repo (not sure if this is the right way to go, but maybe?) - and make each pkgdown have it’s own subdirectory i.e. declaredesign.org/R/estimatr/, declaredesign.org/R/DeclareDesign/ etc.
- [x] Switch host to netlify from Github Pages.
- [x] Start to figure out how to make the blog and pkgdown from the same web site
- [x] Do a nightly Git-based build of the whole Web site
- [ ] Set up workflow that allows an .Rmd to be used for the blog post that can include code chunks, external images saved in some location like /img, plots created by RMarkdown, and also *code chunks that can be collapsed* via js in a simple way.
- [ ] Clean up the discussion board, delete test comments, and go through setup fully. If possible, skin it to look like the rest of the web site.

**Comment by nfultz** [comment]
Re design library - I think it may make sense to split that out into it's
own "package". Hopefully if you get things working for 1 package, then
additional packages are easy to add.

**Comment by Nick-Rivera** [comment]
OK this is a list of what I’ve found out so far. I’ll keep this here for future reference...

I was looking into seeing if blogdown and pkgdown render their pages in the same way. If they do, it would be a lot easier to render all the files in blogdown vs. a weird combo between blogdown and pkgdown.

blogdown uses `rmarkdown::html_document()` to render its pages into HTML. Then, once that’s done, Hugo comes in and takes that HTML and does some processing on it to convert it into a fully featured website. Right now, using Netlify, `rmarkdown::html_document` has to be done outside of Netlify (e.g. on a local computer), and then Netlify can run Hugo to process rmarkdown’s output.

From what I understand, pkgdown does a mix of things for different types of articles. It runs `rmarkdown::html_document()` on Articles to turn them into HTML pages, but from what I can tell it doesn’t do this for other types of pages (e.g. the homepage or reference pages).

I’ve tried turning vignette markdown files into HTML pages with blogdown and it works well because here blogdown and pkgdown are doing the same thing. So that’s cool.

I’m still not sure what to do with other pages, because it looks like pkgdown does a lot of processing on them. I’ll look into that next.

**Comment by graemeblair** [comment]
Thanks Nick. Seems like travis might be needed then to process the .Rmd files (better if we can have a nightly automated process rather than us running them). Perhaps @nfultz can help.

**Comment by nfultz** [comment]
For figuring out which pieces of pkgdown to cannablize, the comments in
ahttps://github.com/aaronrudkin/pkgdown/blob/master/R/package.r and  also
https://github.com/aaronrudkin/pkgdown/blob/master/R/build-reference.R#L165
might be helpful.

**Comment by Nick-Rivera** [comment]
I looked at the code that creates the HTML in pkgdown and blogdown to see what they’re doing differently.

blogdown takes
Rmd files —> special HTML files that Hugo can understand —> Hugo integrates these pages into a complete site (header, footer, etc…)

pkgdown takes
rmd files for articles —> html pages —> postprocessing by pkgdown (specifically, it uses `format()` and `update_rmarkdown_html()`.

non rmd files —> interpreted by pkgdown —> turned into HTML through whisker

It would be best to sketch out what the site should look like (i.e. what elements should go where). Right now, moving the Design Library page and The Idea pages into blogdown is no problem because they’re RMD files. All I need to know is where to put what. The, I could work on 

>  Set up workflow that allows an .Rmd to be used for the blog post that can include code chunks, external images saved in some location like /img, plots created by RMarkdown, and also code chunks that can be collapsed via js in a simple way.

But, it would be hard to render everything that pkgdown does with only pure, untouched  blogdown, because blogdown was only built to render rmd documents. From what I understand, blogdown would have a hard time with reference files. That would be a bigger task.
