### ISSUE TITLE
Design library table

### ISSUE THREAD

**Issue by Nick-Rivera** [DeclareDesign/declaredesign.org#37]
Each design+designer combo should have one entry in the table. If a vignette exists for that design+designer combo, put a link to that in the table.

Also, include specific vignettes into the table (as indicated in their YAML header). If these vignettes don't have an associated design+designer combo, links to the design+designer should be greyed out.

- [x] Figure out best way to link vignette, design, and designer
- [x] Figure out how to add quicksort options to the table
For next time:
- [x] If the vignette doesn't exist, then should I pick out the title from the designer or the design (e.g. An audit experiment design vs Create an audit experiment design) (pick the shorter one)

**Comment by jaspercooper** [comment]
awesome, thanks @Nick-Rivera 

Here's an example:
- Entry under Design is from the `title` variable in the yaml, and hyperlinked to the vignette when it exists, when the vignette doesn't exist this can be pulled from the function documentation
- Designer is a link to the reference page for the function when it exists (linked to in the vignette through the yaml when there's a vignette)
- Author gets pulled from the documentation of the designer function
- Keywords get pulled from the `@concept` tags in the documentation for the designer
- Example design is the design object in the package when it exists and can be pointed to from yaml too

| Design                | Designer                | Author             | Keywords   | Example design        |
|-----------------------|-------------------------|--------------------|------------|-----------------------|
| Simple two-arm design | simple_two_arm_designer | DeclareDesign Team | experiment | simple_two_arm_design |

**Comment by jaspercooper** [comment]
@graemeblair is this along the lines of what you were envisioning, as a replacement of the reference page?

**Comment by graemeblair** [comment]
Yes! Looks great!

**Comment by jaspercooper** [comment]
Wishlist, I realize much of this is hard but would be great to have:

- [ ] Glyphicons to download Rdata for each design
- [ ] direct link to shiny app for each designer
- [ ] subset table by clicking on keyword
- [ ] sort table by column
- [ ] search tool

**Comment by graemeblair** [comment]
can we add to this removing the "how to write and contribute" from the table? I know it's a vignette but presumably we can exclude. can we also change "Getting Started" pulldown to just a link "Contributing" or "Contribute"?

**Comment by jaspercooper** [comment]
Thanks for bringing this up Graeme -- We've been meaning to do this since the beginning. I believe this will be fixed when we move to the "master table" implementation: only designs / designers / vignettes in the database table will be added to the website table. 

@Nick-Rivera maybe we'll need a YAML argument or something to make clear that those "how to" vignettes get added to the dropdown? 

I like the idea of calling it "contributing". Then each sub-option on the dropdown can just be a vignette corresponding to the thing you can contribute:

Contributing
- Designs
- Designers

**Comment by Nick-Rivera** [comment]
Right now, we can add menu items to the dropdown in the `config.toml` file. Maybe we can talk about specifying menu options in the YAML somehow.

**Comment by Nick-Rivera** [comment]
Where should the icon to download Rdata go? Should it have its own column in the table, next to `example design`?

**Comment by graemeblair** [comment]
What's the RData, the design object?

**Comment by Nick-Rivera** [comment]
Yep they're the design objects.

**Comment by graemeblair** [comment]
Thanks. I think it should replace the text in example design, i.e. in that column there should just be the icons. (This is because the name of the design already appears twice!) I think similarly the icon for the designer should replace the text in column 2. Does that sound right to you?

**Comment by jaspercooper** [comment]
Sounds great. Also there's no need to point to the documentation page for designs any more. We're going to remove them from the package and the documentation along with them. So when we click on the icon the design should just download.

The table looks really great, nice work!

**Comment by Nick-Rivera** [comment]
Should the link to the documentation be there for the designers?

**Comment by jaspercooper** [comment]
Yes. Definitely for the designers just not for the designs
