### ISSUE TITLE
Overview table wishlist

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/declaredesign.org#40]
A wishlist for the overview table (much of which I realize may be hard and will require plugins):

- [ ] Glyphicons to download Rdata for each design
- [ ] direct link to shiny app for each designer
- [ ] subset table by clicking on keyword
- [ ] sort table by column
- [ ] search tool

Migrated from https://github.com/DeclareDesign/DesignLibrary/issues/71

**Comment by jaspercooper** [comment]
Migrated to #37 

Was looking at the github.io repo before
