### ISSUE TITLE
building each component separately

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/declaredesign.org#47]
Posting per discussion last week

ie. fabricatr / estimatr / DeclareDesign / design library / etc. should be built separately and if there is an error, it should just not push that part of the web site but the rest should build and push. Currently if one page is broken anywhere nothing builds.

**Comment by Nick-Rivera** [comment]
Tasks:

- [ ] Build each package separately per Graeme's description.
- [ ] Move all constants to one config file so they're not separated across all of the code files.
- [ ] Remove as many hacks as possible. For hacks that have to stay, document them.
