### ISSUE TITLE
headers

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/declaredesign.org#49]
Can we move about to the right of packages?

And, more important, can we add some horizontal space between the menus that change per site and the packages pull down? To visually differentiate the general navigation from per-package navigation.

**Comment by Nick-Rivera** [comment]
Should the `about` link show up on all the packages' pages, or just on the home page. Right now, it only shows up on the home page.

**Comment by graemeblair** [comment]
you're right. thanks, let's leave as is. 

can you remove it from the design library page? that seems to be the other place it is. thx!
